use mamba::Arguments;
use tests_util::OutTestRet;

use test_case::test_case;

#[test_case("access", "simple_index")]
#[test_case("access", "dictionary_access")]
#[test_case("access", "simple_list_access")]
#[test_case("access", "index_via_function")]
#[test_case("access", "access_string")]
#[test_case("call", "call_with_class_child")]
#[test_case("call", "input")]
#[test_case("class", "assign_to_nullable_field")]
#[test_case("class", "cyclic_field_dependency")]
#[test_case("class", "generics")]
#[test_case("class", "field_depends_on_later_field")]
#[test_case("class", "field_deps_operators")]
#[test_case("class", "field_deps_collections")]
#[test_case("class", "assign_types_nested")]
#[test_case("class", "class_super_one_line_init")]
#[test_case("class", "assign_types_double_nested")]
#[test_case("class", "print_types_double_nested")]
#[test_case("class", "import")]
#[test_case("class", "generic_unknown_type_unused")]
#[test_case("class", "same_var_different_type")]
#[test_case("class", "doc_strings")]
#[test_case("class", "fun_with_body_in_interface")]
#[test_case("class", "multiple_parent")]
#[test_case("class", "shadow")]
#[test_case("class", "parent")]
#[test_case("class", "types")]
#[test_case("class", "trait_and_type")]
#[test_case("class", "top_level_tuple")]
#[test_case("class", "with_generics" => ignore["why is Outerclass undefined?"])]
#[test_case("class", "top_level_unassigned_but_nullable")]
#[test_case("class", "unassigned_tuple_second_nullable")]
#[test_case("class", "var_from_outside_class")]
#[test_case("collection", "collection_type")]
#[test_case("collection", "infer_collection_type")]
#[test_case("collection", "infer_collection_type_for_fun")]
#[test_case("collection", "list")]
#[test_case("collection", "list_assign")]
#[test_case("collection", "list_round_bracket_index")]
#[test_case("collection", "dictionary")]
#[test_case("collection", "dictionary_assign")]
#[test_case("collection", "dictionary_round_bracket_index")]
#[test_case("collection", "dictionary_builder")]
#[test_case("collection", "dictionary_in_fun")]
#[test_case("collection", "nested_list_builder")]
#[test_case("collection", "nested_set_builder")]
#[test_case("collection", "set")]
#[test_case("collection", "set_union")]
#[test_case("control_flow", "assign_if")]
#[test_case("control_flow", "assign_match")]
#[test_case("control_flow", "class_field_assigned_to_both_branches_if")]
#[test_case("control_flow", "class_field_assigned_to_exhaustive_match")]
#[test_case("control_flow", "double_assign_if")]
#[test_case("control_flow", "for_statements")]
#[test_case("control_flow", "handle_in_if")]
#[test_case("control_flow", "for_over_collection_of_tuple")]
#[test_case("control_flow", "for_over_type_union" => ignore["trips up when comparing range_iterator and str_iterator"])]
#[test_case("control_flow", "for_over_range_from_func")]
#[test_case("control_flow", "if")]
#[test_case("control_flow", "if_in_if_cond")]
#[test_case("control_flow", "if_in_for_loop" => ignore["See #367"])]
#[test_case("control_flow", "if_two_types")]
#[test_case("control_flow", "match_dont_remove_shadowed")]
#[test_case("control_flow", "matches_in_if")]
#[test_case("control_flow", "shadow_in_if_arms")]
#[test_case("control_flow", "shadow_in_if_arms_then")]
#[test_case("control_flow", "shadow_in_if_arms_else")]
#[test_case("control_flow", "while")]
#[test_case("control_flow", "match_stmt")]
#[test_case("definition", "long_f_string")]
#[test_case("definition", "assign_tuples")]
#[test_case("definition", "assign_to_nullable_in_function")]
#[test_case("definition", "all_mutable_in_call_chain" => ignore["nested calls not checked properly: #482"])]
#[test_case("definition", "nested_mut_field")]
#[test_case("definition", "assign_to_inner_mut" => ignore["nested calls not checked properly: #482"])]
#[test_case("definition", "nested_function" => ignore["nested calls not checked properly: #482"])]
#[test_case("definition", "tuple_modify_mut")]
#[test_case("definition", "tuple_modify_outer_mut")]
#[test_case("definition", "f_strings" => ignore["cannot nest strings: #481"])]
#[test_case("definition", "collection_in_f_strings")]
#[test_case("definition", "assign_with_if")]
#[test_case("definition", "assign_with_if_different_types" => ignore["annotating output reveals bug in check stage"])]
#[test_case("definition", "assign_with_match")]
#[test_case("definition", "assign_with_match_different_types" => ignore["annotating output reveals bug in check stage"])]
#[test_case("definition", "assign_with_match_type_annotation")]
#[test_case("definition", "assign_with_nested_if")]
#[test_case("definition", "assign_with_try_except")]
#[test_case("definition", "function_ret_super_in_class")]
#[test_case("definition", "function_no_return_type")]
#[test_case("definition", "function_with_if")]
#[test_case("definition", "function_with_if_and_raise")]
#[test_case("definition", "function_with_nested_if")]
#[test_case("definition", "function_with_match")]
#[test_case("definition", "ternary")]
#[test_case("definition", "function_ret_super")]
#[test_case("definition", "tuple_non_lit_modify_mut")]
#[test_case("error", "handle")]
#[test_case("error", "handle_only_id")]
#[test_case("error", "exception")]
#[test_case("error", "exception_in_fun")]
#[test_case("error", "handle_var_usable_after")]
#[test_case("error", "exception_in_fun_super")]
#[test_case("error", "nested_exception")]
#[test_case("error", "raise")]
#[test_case("error", "with")]
#[test_case("function", "callable_fun_arg")]
#[test_case("function", "divmod")]
#[test_case("function", "hello_world")]
#[test_case("function", "pure_function")]
#[test_case("function", "infer_default_arg_type")]
#[test_case("function", "calls")]
#[test_case("function", "definition")]
#[test_case("function", "function_with_defaults")]
#[test_case("function", "function_raise_super")]
#[test_case("function", "match_function")]
#[test_case("function", "print_string")]
#[test_case("function", "return_last_expression")]
#[test_case("function", "ternary_function_call")]
#[test_case("function", "exception_and_type")]
#[test_case("function", "allowed_exception")]
#[test_case("function", "allowed_pass")]
#[test_case("operation", "arithmetic")]
#[test_case("operation", "assign_types")]
#[test_case("operation", "assign_types_no_annotation" => ignore["See if we can modify type checker so it takes largest common"])]
#[test_case("operation", "assign_types_nested")]
#[test_case("operation", "greater_than_int")]
#[test_case("operation", "less_than_equal_int")]
#[test_case("operation", "greater_than_other_int")]
#[test_case("operation", "in_set_is_bool")]
#[test_case("operation", "multiply_other_int")]
#[test_case("operation", "primitives")]
#[test_case("operation", "boolean")]
#[test_case("operation", "equality_different_types")]
#[test_case("operation", "type_alias_primitive" => ignore["investigate whether this should in fact, pass"])]
#[test_case("readme_example", "builtin_trait" => ignore["@ decorator syntax and meta trait/external impl for a built-in type not implemented"])]
#[test_case("readme_example", "class_with_constants")]
#[test_case("readme_example", "class")]
#[test_case("readme_example", "error_handling_as_expression")]
#[test_case("readme_example", "error_handling_desyntax_sugared" => ignore["match case cannot bind an error's constructor arguments yet (err: Type(args))"])]
#[test_case("readme_example", "error_handling_early_exit")]
#[test_case("readme_example", "error_handling_handle_subset" => ignore["explicit Result[...] type and re-raising via `<var> = <var> !` not implemented"])]
#[test_case("readme_example", "error_handling" => ignore["isa operator and match case capturing an error's constructor arguments not implemented"])]
#[test_case("readme_example", "factorial_dynamic" => ignore["--annotate generates invalid Python for a shadowed loop var that is also a match case's tail expression (documented as still buggy in the CLI help)"])]
#[test_case("readme_example", "factorial")]
#[test_case("readme_example", "impl_trait" => ignore["`def <Trait> for <Class> where ...` external-implementation syntax and meta modifier not implemented"])]
#[test_case("readme_example", "list_shorthand")]
#[test_case("readme_example", "lists" => ignore["list/set/dict builder syntax binding more than one variable is not resolved by the checker"])]
#[test_case("readme_example", "mutability")]
#[test_case("readme_example", "pure_functions" => ignore["range .step(...) method not implemented"])]
#[test_case("readme_example", "sets_maps" => ignore["list/set/dict builder syntax binding more than one variable is not resolved by the checker"])]
#[test_case("readme_example", "total_functions" => ignore["`total` keyword not implemented"])]
#[test_case("readme_example", "trait_fin_meta" => ignore["meta/fin modifiers on trait methods not implemented"])]
#[test_case("readme_example", "trait_inheritance" => ignore["composing multiple parent traits not implemented"])]
#[test_case("readme_example", "traits" => ignore["generics on traits and external-implementation syntax not implemented"])]
fn to_python(input_dir: &str, file_name: &str) -> OutTestRet {
    tests_util::test_directory(true, &[input_dir], &[input_dir, "target"], file_name)
}

#[test_case("collection", "tuple", Arguments { annotate: false, ..Arguments::default() })]
fn to_python_with_args(input_dir: &str, file_name: &str, args: Arguments) -> OutTestRet {
    tests_util::test_directory_args(true, &[input_dir], &[input_dir, "target"], file_name, &args)
}
