#!/bin/bash

. ./scripts/log.sh
export LOG_LEVEL=4 # debug

set -euo pipefail

log_info "Running pre-push checks"

for script in "$(dirname "$0")/pre-push"*; do
    if [ "$script" = "$0" ]; then
        continue # dont run self
    fi

    "$script" $@
done

log_info "Pre-push checks passed"
