#!/bin/bash

. ./.githooks/log

log_trace "Loaded githook utils"

min_bash_version() {
    should_run=$1
    min_version=$2

    if [[ -z "${BASH_VERSINFO+set}" ]]; then
        log_error "This script must be run under bash"
    fi

    major=${BASH_VERSINFO[0]}
    _minor=${BASH_VERSINFO[1]}

    if (( major < min_version )); then
        log_warning "Detected Bash version $BASH_VERSION, cannot run '$should_run' check  (requires bash >4.0)"
    fi
}
