# Appveyor configuration template for Rust using rustup for Rust installation
# https://github.com/starkat99/appveyor-rust

os: Visual Studio 2015

environment:
  matrix:

### MSVC Toolchains ###

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

  - rustup component add rustfmt --toolchain nightly
  - if %channel% == "stable" rustup component add clippy

  - rustc -vV
  - cargo -vV

# cargo does this for us
build: false
test_script:
  # fail when formatting error encountered
  - cargo +nightly fmt --all -- --check
  # fail when encountering clippy warnings
  - if %channel% == "stable"  cargo clippy -- -D warnings
  - cargo test --verbose

# Skip commits
skip_commits:
  files:
  - '*.md'
  - .gitignore
