theme: jekyll-theme-minimal

title: Mamba
description: This is the page of the Mamba repo itself. For the documentation check out the docs <a href="https://joelabrahams.nl/mamba_doc">here</a>

logo: /image/logo_medium.png
