[package]
name = "mamba"
version = "0.3.6"
authors = ["Joël Abrahams <abrahamsjo@gmail.com>"]
description = "A transpiler which converts Mamba files to Python 3 files"
edition = "2021"
license-file = "LICENSE"
rust-version = "1.80.0"

readme = "README.md"
repository = "https://github.com/JSAbrahams/mamba"
keywords = ["python", "transpiler", "compiler"]
categories = ["parsing"]

[dependencies]
ansi_term = "0.12.1"
assert_cmd = "0.10"
clap = { version = "2.33", features = ["yaml"] }
glob = "0.3.0"
itertools = "0.8.2"
log = "0.4"
loggerv = "0.7"
pathdiff = "0.1.0"
permutate = "0.3.2"
python-parser = "0.1.0"
tempfile = "3.1.0"

[dev-dependencies]
test-case = "3.3.1"
