[package]
name = "tests_util"
authors = ["Joël Abrahams"]
description = "Test and benchmark utilities"
edition = "2021"

[dependencies]
# we must allow ourselves one circular dependency
mamba = { path = ".." }
ruff_python_ast = "0.0.13"
ruff_python_parser = "0.0.13"
itertools = "0.8.2"
tempfile = "3.1.0"
assert_cmd = "0.10"
