use crate::parser::ast::{Node, AST};
use crate::type_checker::environment::infer_type::InferType;

pub struct Constraint {
    ast: AST,
    ty:  InferType
}

pub fn generate(ast: &AST, constr: &[Constraint]) -> Vec<Constraint> {
    match &ast.node {
        Node::File { .. } => unimplemented!(),
        Node::Import { .. } => unimplemented!(),
        Node::FromImport { .. } => unimplemented!(),
        Node::Class { .. } => unimplemented!(),
        Node::Generic { .. } => unimplemented!(),
        Node::Parent { .. } => unimplemented!(),
        Node::Script { .. } => unimplemented!(),
        Node::Init => unimplemented!(),
        Node::Reassign { .. } => unimplemented!(),
        Node::VariableDef { .. } => unimplemented!(),
        Node::FunDef { .. } => unimplemented!(),
        Node::AnonFun { .. } => unimplemented!(),
        Node::Raises { .. } => unimplemented!(),
        Node::Raise { .. } => unimplemented!(),
        Node::Handle { .. } => unimplemented!(),
        Node::With { .. } => unimplemented!(),
        Node::ConstructorCall { .. } => unimplemented!(),
        Node::FunctionCall { .. } => unimplemented!(),
        Node::PropertyCall { .. } => unimplemented!(),
        Node::Id { .. } => unimplemented!(),
        Node::IdType { .. } => unimplemented!(),
        Node::TypeDef { .. } => unimplemented!(),
        Node::TypeAlias { .. } => unimplemented!(),
        Node::TypeTup { .. } => unimplemented!(),
        Node::TypeUnion { .. } => unimplemented!(),
        Node::Type { .. } => unimplemented!(),
        Node::TypeFun { .. } => unimplemented!(),
        Node::Condition { .. } => unimplemented!(),
        Node::FunArg { .. } => unimplemented!(),
        Node::_Self => unimplemented!(),
        Node::AddOp => unimplemented!(),
        Node::SubOp => unimplemented!(),
        Node::SqrtOp => unimplemented!(),
        Node::MulOp => unimplemented!(),
        Node::FDivOp => unimplemented!(),
        Node::DivOp => unimplemented!(),
        Node::PowOp => unimplemented!(),
        Node::ModOp => unimplemented!(),
        Node::EqOp => unimplemented!(),
        Node::LeOp => unimplemented!(),
        Node::GeOp => unimplemented!(),
        Node::Set { .. } => unimplemented!(),
        Node::SetBuilder { .. } => unimplemented!(),
        Node::List { .. } => unimplemented!(),
        Node::ListBuilder { .. } => unimplemented!(),
        Node::Tuple { .. } => unimplemented!(),
        Node::Range { .. } => unimplemented!(),
        Node::Block { .. } => unimplemented!(),
        Node::Real { .. } => unimplemented!(),
        Node::Int { .. } => unimplemented!(),
        Node::ENum { .. } => unimplemented!(),
        Node::DocStr { .. } => unimplemented!(),
        Node::Str { .. } => unimplemented!(),
        Node::Bool { .. } => unimplemented!(),
        Node::Add { .. } => unimplemented!(),
        Node::AddU { .. } => unimplemented!(),
        Node::Sub { .. } => unimplemented!(),
        Node::SubU { .. } => unimplemented!(),
        Node::Mul { .. } => unimplemented!(),
        Node::Div { .. } => unimplemented!(),
        Node::FDiv { .. } => unimplemented!(),
        Node::Mod { .. } => unimplemented!(),
        Node::Pow { .. } => unimplemented!(),
        Node::Sqrt { .. } => unimplemented!(),
        Node::BAnd { .. } => unimplemented!(),
        Node::BOr { .. } => unimplemented!(),
        Node::BXOr { .. } => unimplemented!(),
        Node::BOneCmpl { .. } => unimplemented!(),
        Node::BLShift { .. } => unimplemented!(),
        Node::BRShift { .. } => unimplemented!(),
        Node::Le { .. } => unimplemented!(),
        Node::Ge { .. } => unimplemented!(),
        Node::Leq { .. } => unimplemented!(),
        Node::Geq { .. } => unimplemented!(),
        Node::Is { .. } => unimplemented!(),
        Node::IsN { .. } => unimplemented!(),
        Node::Eq { .. } => unimplemented!(),
        Node::Neq { .. } => unimplemented!(),
        Node::IsA { .. } => unimplemented!(),
        Node::IsNA { .. } => unimplemented!(),
        Node::Not { .. } => unimplemented!(),
        Node::And { .. } => unimplemented!(),
        Node::Or { .. } => unimplemented!(),
        Node::IfElse { .. } => unimplemented!(),
        Node::Match { .. } => unimplemented!(),
        Node::Case { .. } => unimplemented!(),
        Node::For { .. } => unimplemented!(),
        Node::In { .. } => unimplemented!(),
        Node::Step { .. } => unimplemented!(),
        Node::While { .. } => unimplemented!(),
        Node::Break => unimplemented!(),
        Node::Continue => unimplemented!(),
        Node::Return { .. } => unimplemented!(),
        Node::ReturnEmpty => unimplemented!(),
        Node::Underscore => unimplemented!(),
        Node::Undefined => unimplemented!(),
        Node::Pass => unimplemented!(),
        Node::Question { .. } => unimplemented!(),
        Node::QuestionOp { .. } => unimplemented!(),
        Node::Print { .. } => unimplemented!(),
        Node::Comment { .. } => unimplemented!()
    }
}
