name: Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_binary_size:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]

    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
