name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python: [ "3.10" ]
        rust: [ "1.81.0" ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python v${{ matrix.python }}, Rust ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v2

      # Install Python
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Install Rust, build and check clippy warnings
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
          override: true

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --package mamba
