name: Coverage

on:
  push:
    branches: [ master, develop ]
  pull_request:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python: [ "3.10" ]
        rust: [ "nightly" ]

    runs-on: ${{ matrix.os }}

    steps:
      # Install Python
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Checkout and use nigthly toolchain
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Grcov
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      # Run grcov, which outputs a report
      - uses: actions-rs/grcov@v0.1
        id: coverage

      - name: Codecov upload
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.coverage.outputs.report }}
