name: Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ${{ matrix.os }}

    name: OS ${{ matrix.os }}, Rust ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
