name: Test

on:
  push:
    branches: [ master, develop ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python: [ "3.10" ]
        rust: [ "nightly" ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python v${{ matrix.python }}, Rust ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v2

      # Install Python
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Install Rust, build and check clippy warnings
      - name: Install Rust ${{ matrix.rust }}
        run: rustup toolchain install ${{ matrix.rust }}

      # Run tests
      - name: Build Nightly
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo +nightly build
      - name: Run tests Nightly
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo +nightly test --package mamba

      - name: Build
        if: ${{ matrix.rust != 'nightly' }}
        run: cargo build
      - name: Run tests
        if: ${{ matrix.rust != 'nightly' }}
        run: cargo test --package mamba

