name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        python: [ "3.8" ]
        rust: [ "nightly" ]

    runs-on: ${{ matrix.os }}

    name: OS ${{ matrix.os }}, Python v${{ matrix.python }}, Rust ${{ matrix.rust }}

    steps:
      - uses: actions/checkout@v2

      # Install Python
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Install Rust, build and check clippy warnings
      - name: Install Rust ${{ matrix.rust }}
        run: rustup toolchain install ${{ matrix.rust }}

      # Run tests
      - name: Build Nightly
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo +nightly build
      - name: Run tests Nightly
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo +nightly test --package mamba

      - name: Build
        if: ${{ matrix.rust != 'nightly' }}
        run: cargo build
      - name: Run tests
        if: ${{ matrix.rust != 'nightly' }}
        run: cargo test --package mamba

      # Code Coverage
      - name: Clean
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions-rs/toolchain@v1
        with:
          command: clean
          toolchain: nightly
          override: true

      # Must install for code coverage
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Grcov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

      # Run grcov, which outputs a report
      - uses: actions-rs/grcov@v0.1
        id: coverage

      - name: Codecov upload
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
        with:
          files: ${{ steps.coverage.outputs.report }}
